import { createContext } from "react";

export default createContext({
    initialMoney : 0,
    sales : 0,
    currentChange : 0,
    hasValidateAdmin : false,
    listStores : [],
    nameStoreSelected : "",
    boxesOpen : null,
    detailVentasxBox : null,
    sumTotalVentas : null,
    sumTotalEfectivo : null,
    sumTotalTarjetas : null,
    sumTotalYape : null,
    sumTotalPlin : null,
    montoApertura : null,
    hasBoxesOpen : false,
    dataBoxesOpen : [],
    mostrarAlertaAperturaCaja : false,
    existeCajasAbiertas : false,
    montoCierreCaja : 0,
    actualizarData : false,
    handleAddSales : ()=>{},
    saveStoreSelected : (storeSelected)=>{},
    saveNameStoreSelected : (nameStore)=>{},
    saveCurrentChange : (data)=>{},
    changeValidateAdmin:()=>{},
    saveBoxesOpen : ()=>{},
    saveSumTotalVentas:()=>{},
    saveDetailVentas : ()=>{},
    saveSumTotalEfectivo : ()=>{},
    saveSumTotalTarjetas : ()=>{},
    saveSumTotalYape : ()=>{},
    saveSumTotalPlin : ()=>{},
    llamarDataCajaPorIdTienda : async()=>{},
    saveMontoApertura : (nuevoMontoApertura)=>{},
    removeBoxOpen : (idBoxOpen)=>{},
    saveListStores :(listStores)=>{},
    saveExisteCajasAbiertas : (existeCajasAbiertas)=>{},
    saveDataBoxesOpen:(boxesOpen)=>{},
    changeVisibleAlertAperturaCaja : ()=>{},
    saveMontoCierreCaja : ()=>{},
    actualizarDataCaja : async()=>{}
})