import {createContext} from 'react';
export default createContext({
    numProducts : 0,
    listProducts :[],
    products : [],
    dataInventory :{},
    loadingPage : false,
    registroIngreso : false,
    historyListProducts : [],
    listSuppliers : [ ],
    historyListSupplier:[],
    listStores : [],
    listCategories : [],
    defaultStore : null,
    handleChangeProductStandard :()=>{},
    changeQuerySupplier:(text)=>{},
    saveHistoryListSuppplier:(dataListSupplier)=>{},
    saveListSupplier:(dataListSupplier)=>{},
    handleAddProduct : async(idProducto,product)=>{},
    handleMinusProduct : async()=>{},
    handleDeleteProduct : async (idProducto)=>{},
    clearStorageDataProduct : async()=>{},
    addProductsInventory : async()=>{},
    addSupplierStore : ()=>{},
    handleSubmitProductsInventory : async()=>{},
    changeQuery :(query)=>{},
    filtrarPorCategoria : (categoria)=>{},
    initialValueSupplierStore : (dataSupplier, dataStore)=>{},
    handleAddSupplier : (dataSupplier)=>{},
    handleAddStore : (dataStore)=>{},
    onChangeStore : (newListStore)=>{},
    onChangeSupplier : (newListSupplier)=>{},
    saveListStores :(dataListStore)=>{}

});