name: Build APK

on:
  push:
    branches:
      - main  # O la rama que prefieras para activar el workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y android-sdk
        echo "sdk.dir=/usr/lib/android-sdk" > local.properties

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install dependencies
      run: |
        npm install

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK to GitHub as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
